# BEGIN HRP Cache Bust
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_METHOD} GET [NC]
RewriteCond %{QUERY_STRING} !(^|&)hrpv=
RewriteCond %{REQUEST_URI} !^/wp-(admin|content|includes|json|cron) [NC]
RewriteCond %{REQUEST_URI} !^/(xmlrpc\.php|favicon\.ico) [NC]
RewriteCond %{REQUEST_URI} !\.(css|js|mjs|map|jpe?g|png|gif|webp|ico|svg|woff2?|ttf|eot|txt|xml|pdf|zip|gz)$ [NC]
RewriteRule ^(.*)$ /$1?hrpv=0.3.7 [R=302,L,QSA]
</IfModule>
# END HRP Cache Bust
